#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <daqhats/daqhats.h>

int main(int argc, char* argv[])
{
    uint8_t address;
    uint8_t channel;
    uint8_t value;
    int done;

    // Use MCC 152 at address 0
    address = 0;
    channel = 0;

    if (mcc152_open(address) != RESULT_SUCCESS)
    {
        printf("No MCC 152 at address 0\n");
        return 1;
    }

    // reset to default DIO settings
    mcc152_dio_reset(address);
    
    // read initial value
    mcc152_dio_input_read(address, channel, &value);
    printf("Current channel %d value is %d\n", channel, value);
    printf("Waiting for change\n");
    
    // enable interrupt only on this channel, mask all others
    mcc152_dio_interrupt_mask_write(address, DIO_CHANNEL_ALL, ~(1 << channel));
    
    // Wait for the input to change.  The interrupt can also be generated by another MCC 152 if it 
    // is configured for interrupts; monitoring multiple boards is beyond the scope of this example.
    done = 0;
    do
    {
        // wait forever for interrupt
        hat_wait_for_interrupt(-1);
        // interrupt occurred, determine the source
        mcc152_dio_interrupt_status_read(address, channel, &value);
        if (value != 0)
        {
            done = 1;
        }
        mcc152_dio_input_read(address, channel, &value);
    } while (!done);
    
    printf("Input changed to %d\n", value);
    
    mcc152_close(address);
    return 0;
}
