.. _mcc152:

MCC 152
=======

2-channel analog output / 8 digital I/O board

- 12-bit D/A converter
- 0 - 5V output
- 5V / 3.3V selectable digital I/O
- Programmable pull-up/pull-down resistors
- 25mA sink per output
- Interrupt on input change

.. image:: images/mcc_152.png
    :align: center
    :alt: MCC 152 circuit board

Board components
----------------
Screw terminals
^^^^^^^^^^^^^^^
- **AO0** to **AO1**: Analog output terminals.
- **DIO0** to **DIO7**: Digital input/output terminals

Status LED
^^^^^^^^^^
The LED turns on when the board is connected to a Raspberry Pi with external power applied. 

Header connector
^^^^^^^^^^^^^^^^
The board header is used to connect with the Raspberry Pi. Refer to :ref:`install` for more information about the  
header connector.
