.. currentmodule:: daqhats

MCC 152 class
=============

Methods
-------

.. autoclass:: mcc152
    :inherited-members:
    :members:

    .. rubric:: Methods

    ==================================================  ========================================================
    Method                                              Description
    --------------------------------------------------  --------------------------------------------------------
    :py:func:`mcc152.address`                           Read the board's address.
    :py:func:`mcc152.serial`                            Read the serial number.
    :py:func:`mcc152.a_out_num_channels`                Get the number of analog output channels.
    :py:func:`mcc152.a_out_write`                       Write an analog output channel.
    ==================================================  ========================================================
