.. currentmodule:: daqhats

Global methods and data
=======================

Methods
-------

=======================  =======================================================
Method                   Description
-----------------------  -------------------------------------------------------
:py:func:`hat_list`      Return a list of detected DAQ HAT boards.
=======================  =======================================================

.. autofunction:: hat_list

Data
----

Hat IDs
~~~~~~~

.. autoclass:: HatIDs
    :members:

Trigger modes
~~~~~~~~~~~~~

.. autoclass:: TriggerModes
    :members:

HatError class
--------------

.. autoexception:: HatError
